# For VSCode extension https://marketplace.visualstudio.com/items?itemName=GraphQL.vscode-graphql
# The extension settings to specify a custom path for this files don't seem to work.

# Seems to only use the first project's schema. Can toggle between them.
# Seems like it may be fixed in an upcoming release of vscode-graphql extension (current: 0.3.16).
# Possibly related issues: https://github.com/dotansimha/graphql-eslint/issues/526, https://github.com/graphql/vscode-graphql/issues/316, https://github.com/cometkim/gatsby-plugin-typegen/issues/113
projects:
  life:
    schema: lib/life/src/service/graph/schema.graphql
  # matt-fyi:
  #   schema: app/matt-fyi/src/__generated__/gatsby-introspection.json
